frontend-opensource-project/speller-front

src/entities/speller/api/speller-service.ts, src/entities/speller/index.ts, src/entities/speller/model/speller-interface.ts, src/pages/results/api/log-copy-action.ts, src/pages/results/ui/results-control.tsx, src/shared/ui/toaster.tsx
- 전체복사 시 미교정 오류어에 대한 로그 API 호출
- `correctInfo` 에서 `crtStr` 값이 없는 경우 미교정 오류어로 판단
- 복사 시 출력되는 토스트에서 발생하는 key 관련 에러 수정
close #82
=> [#82] 전체복사 시 미교정 오류어에 대한 로그 API 호출

src/entities/speller/lib/apply-corrections.ts, src/entities/speller/model/speller-slice.ts, src/pages/results/ui/results-control.tsx
- 원복 텍스트(`str`)가 아닌 교정된 텍스트(`displayText`)가 복사되도록 수정하였습니다.
- slice에 교정 텍스트를 관리할 displayText 상태를 새로 추가했습니다. 단어가 교정될 때 displayText도 업데이트됩니다.
close #104
=> fix: 교정단어 클릭 시 기존 문장이 복사되는 문제 (#104)

src/pages/results/ui/strong-check-message.tsx
- 강한 검사 여부 문구가 항상 섹션의 우측에 배치되도록 스타일을 수정하였습니다.
=> design: 강한 검사 여부 문구 스타일 수정 (#122)

src/shared/ui/header.tsx
모바일 메뉴에 사용법 페이지 링크 연결이 되어있지 않아 추가하였습니다.
=> fix: 모바일 메뉴에 사용법 페이지 링크 추가 (#134)

src/pages/results/ui/results-page.tsx, src/pages/results/ui/strong-check-message.tsx
- 탭, pc에서 페이지 버튼이 가운데에 오도록 수정하였습니다.
=> design: 페이지버튼 가운데 정렬 (#132)

src/pages/results/ui/help-section.tsx
- 디바이스별 도움말 자세히 보기 버튼의 노출 조건을 정의하였습니다.
close #119
=> feat: "자세히 보기" 버튼 노출 조건 수정 (#119)

src/entities/speller/model/speller-refs-context.tsx, src/pages/results/ui/error-tracking-section.tsx, src/pages/results/ui/spelling-correction-text.tsx
- 맞춤법/문법 오류 섹션에서 대치어에 마우스 오버 시 교정 문서 섹션에서 일치하는 대치어가 최상단으로 스크롤되는 기능을 추가했습니다.
=> feat: 맞춤법/문법 오류 섹션 대치어에 마우스 오버 시 교정 문서 섹션 스크롤 (#167)

app/order/layout.tsx, app/order/page.tsx, src/pages/order/index.ts, src/pages/order/ui/info-card.tsx, src/pages/order/ui/order-page.tsx, src/pages/order/ui/section-panel.tsx, src/shared/model/contact-info.ts, src/shared/ui/footer.tsx
- 구매문의 페이지 추가 및 반응형 적용
- 모바일, 태블릿 레이아웃은 개발자가 임의로 조정하도록 논의
- 푸터 `구매문의` 링크 호버 스타일 변경
- 구매문의 연락처 모델을 추가하였는데, 초기 시안에는 레이아웃에 헤더/푸터가 없이 페이지 하단에 별도 푸터 UI 를 표시하는거라 연락처 정보 재사용이 필요해 모델을 추가했습니다. ([src/shared/model/contact-info.ts](https://github.com/frontend-opensource-project/speller-front/pull/174/files#diff-5f0f3be8646ec34e0839645c7b6f668eec53ade05fcb2def92fdfa0ce539e744))
- _지금은 헤더/푸터를 포함하는 것으로 시안이 변경되었는데, 이후에 연락처 정보 재사용이 필요할 수도 있을 것 같아 롤백하지는 않았습니다!_
- 다시 연락처 정보 표시하는 것으로 시안 변경되었습니다 :)
=> #163 구매 문의 페이지 추가

src/entities/speller/model/speller-refs-context.tsx, src/pages/results/ui/correction-content.tsx, src/pages/results/ui/error-tracking-section.tsx, src/shared/lib/google-ad-sense.tsx, src/shared/lib/isDesktop.ts, src/shared/lib/use-desktop-or-fallback.ts, src/shared/lib/use-desktop.ts, src/shared/lib/use-device-utils.ts, src/shared/ui/textarea.tsx
작업내용
데스크탑 너비에서 스크롤이 항상 보이도록 개선하고, 관련된 로직을 재사용 가능한 훅으로 분리하여 최적화하였습니다.
https://github.com/user-attachments/assets/70d5a91d-394a-4041-bc17-714636eac692
--- 
변경사항
- 데스크탑 너비에서 스크롤이 항상 활성화되도록 로직 추가
- 원문 / 교정문서 / 맞춤법 오류 섹션에 너비 기반 상태를 반환하는 재사용 훅 작성
- 데스크탑 여부를 판별하는 훅(useDesktop)에 1초 지연(delay)을 통한 최적화 적용
- 데스크탑 여부에 따라 다른 값을 반환하는 훅(useDesktopOrFallback)에 useMemo를 적용해 불필요한 렌더링 방지
=> [#158] 스크롤바가 PC에서는 항상 보이게 수정

src/app/index.tsx, src/entities/speller/model/speller-refs-context.tsx, src/pages/results/ui/correction-content.tsx, src/pages/results/ui/error-tracking-section.tsx, src/shared/lib/google-ad-sense.tsx, src/shared/lib/use-desktop-or-fallback.ts, src/shared/lib/use-desktop.ts, src/shared/lib/use-optimized-scroll-detection.ts, src/shared/ui/base-layout.tsx, src/shared/ui/footer.tsx, src/shared/ui/scroll-container.tsx, src/shared/ui/textarea.tsx
PR 목적
이번 PR은 다음 두 가지 목적을 갖고 있습니다:
1. **OverlayScrollbars 기반 커스텀 스크롤바 컴포넌트 기능 추가**
2. **외부에서 컴포넌트를 사용할 때 발생하는 Ref 동기화 문제 개선**
해당 컴포넌트는 공통 UI 요소로 사용되며, 여러 페이지에서 재사용될 예정입니다.  
특히 외부에서 스크롤을 직접 제어할 경우 발생할 수 있는 제약 사항과 그 해결 방법을 문서화하였습니다.
---
변경 배경
- 초기에는 `textarea` 전용 커스텀 스크롤 컴포넌트로 개발되었습니다.
- 이후 공통 UI로 확장되면서 외부 Ref 연동이 필요해졌습니다.
- 그러나 `OverlayScrollbars`는 초기화 시 DOM 구조를 래핑하고, 네이티브 스크롤 메서드를 오버라이드합니다.
- 기존 방식으로는 외부에서 내부 API에 접근이 불가능하여, 세밀한 스크롤 제어를 위한 API 노출이 필요했습니다.
---
주요 문제점
| 문제 | 설명 |
|------|------|
| Ref 연결 실패 | 외부에서 `ref.current.scrollTo()` 호출 시 동작하지 않음 |
| 스크롤 위치 제어 불가 | DOM이 래핑되어 `scrollTop`, `scrollTo` 방식이 작동하지 않음 |
| 동기화 타이밍 이슈 | `OverlayScrollbars` 초기화 이후 `Ref`가 올바르게 매핑되지 않음 |
| API 사용 충돌 | `OverlayScrollbarsComponent`와 `useOverlayScrollbars`를 동시에 사용하면 비정상 동작 |
| 중첩 스크롤 이슈 | …
=> [#175] (#175 > #161) scroll-container 로직 리팩토링

src/pages/feedback/ui/feedback-form.tsx, src/pages/speller/ui/speller-control.tsx, src/pages/speller/ui/speller-page.tsx, src/pages/speller/ui/speller-text-input.tsx, src/shared/ui/textarea.tsx
PR 목적
이번 PR은 다음 목적을 갖고 있습니다:
1. **Textarea 회귀 결정 및 브라우저 간 이벤트 처리 이슈 대응**
2. **ContentEditable 방식에서 발생한 유지보수 이슈 해소 및 UX 안정성 확보**
3. **useEffect 최소화 처리**
---
변경 배경
초기에는 커스텀 스크롤이 필요한 상황에서 `div[contentEditable]`을 활용하여 textarea와 유사한 UX를 구현했습니다.  
하지만 플랫폼 및 브라우저 간 복잡한 이슈와 버그가 발생했고, 다음과 같은 이유로 **textarea 방식으로 회귀**하게 되었습니다.
---
주요 문제점
| 플랫폼 | 브라우저 | 이벤트 종류 | 동작 여부 |
|--------|----------|-------------|------------|
| Mac    | Safari   | `onPaste`   | 정상 동작 |
|        | Chrome   | `onPaste`   | 정상 동작 |
|        | Edge     | `onPaste`   | 정상 동작 |
| Windows| Chrome   | `onPaste`   | 정상 동작 |
|        | Edge     | `onPaste`   | 정상 동작 |
| iOS    | Chrome   | `onPaste`   | 정상 동작 |
|        | Safari   | `onPaste`   | 정상 동작 |
| Android| Chrome   | ❗ `onInput` | `onPaste` 작동 안함, `innerHTML` 포함 |
|        | …
=> [#164] 복사 후 붙여넣기 시 HTML 요소가 포함되는 이슈 수정

src/entities/speller/model/speller-refs-context.tsx
- 모바일 화면에서 교정 문서, 맞춤법/문법 오류 섹션의 대치어 선택(적용) 시 양 섹션간 스크롤되는 기능을 추가했습니다.
close #180
=> feat: 모바일에서 대치어 적용 시 섹션 스크롤되는 기능 추가 (#180)

src/pages/results/ui/navigator.tsx, src/pages/results/ui/results-page.tsx
- 페이지 이동 시 이전 페이지 섹션의 스크롤 위치가 기억되는 현상을 개선했습니다.
- 페이지가 이동할 때마다 교정 문서와 맞춤법/문법 오류 섹션의 스크롤 위치가 항상 최상단으로 이동하도록 개선했습니다.
=> feat: 페이지 이동 시 섹션 스크롤 초기화하는 기능 (#162)

src/shared/lib/util.ts
- 기존에는 `text.split(/\s+/)`을 사용해 공백 문자 기준으로 텍스트를 나눈 단어 배열에서 단어의 위치를 추정했으나,
공백이 여러 개이거나 줄바꿈(\r\n, \r\r)이 섞인 경우 startIndex와 실제 단어 위치가 어긋나 throw가 발생하는 문제가 있었습니다.
- `text.matchAll(/\S+/g)`을 사용하여 공백이 아닌 실제 단어들을 매칭하면서 각 단어의 시작 위치(index)를 함께 추출하도록 변경했습니다.
- matchAll로부터 가져온 시작 위치를 기반으로 현재 찾으려는 단어 범위내에 있는지 검사하도록 수정되었습니다.
https://github.com/frontend-opensource-project/speller-front/pull/179#issuecomment-2799070026 에서 공유드린 텍스트로 확인한 결과, 에러가 발생하지 않는 것을 확인하였습니다
close #184
=> fix: 복사하기 후 로그 전달 시 에러가 발생하는 문제 수정 (#184)

src/pages/results/ui/spelling-correction-text.tsx
작업내용
- 모바일(AOS, iOS) 환경에서 교정 단위 위에서 드래그 시 끊김이 발생하는 문제를 수정했습니다.
- PC 및 모바일에서 교정된 단어와 원문 단어를 동시에 드래그할 경우, 원문 전체 문장만 정확히 복사되도록 처리했습니다.
- 드래그 후 붙여넣기 시 교정된 단어는 제외되고, 원문 문장만 붙여넣어지도록 개선했습니다.
- 교정 문서 컴포넌트의 불필요한 리렌더링을 일부 최적화했습니다.
- `SpellingCorrectionText` 컴포넌트의 가독성을 높이기 위해 비즈니스 로직을 함수로 분리하고, 각 책임을 명확히 했습니다.
작업물
문제 버전 (AOS, iOS 동일)
https://github.com/user-attachments/assets/4622f87d-1382-4f10-a117-b5b24754a3b6
개선 버전 (AOS, iOS 동일)
https://github.com/user-attachments/assets/e7f5a615-f375-473a-9e9e-4773b717e049
성능 최적화
| 항목                                   | 최적화 전         | 최적화 후         | 개선 효과                  |
|----------------------------------------|-------------------|-------------------|----------------------------|
| 렌더링 duration (CorrectionText)       | 최대 10.1ms       | 최대 2.5ms        | 약 …
=> [#185] 텍스트 드래그 시 끊김 및 복사 동작 개선, 성능 최적화

src/entities/speller/model/speller-refs-context.tsx, src/pages/results/ui/error-tracking-section.tsx, src/pages/results/ui/spelling-correction-text.tsx
맞춤법 결과 페이지 렌더링후, 마우스오버 이벤트가 발생해도 스크롤이 발생하지 않는 이슈가 발생했습니다.
기존에는 리스트 렌더링 시 createRef() 방식으로 ref 배열을 초기화하고, 각 요소에 다음과 같이 연결했습니다:
```ts
const correctRefs = Array.from(
{ length: correctInfo.length },
() => createRef<HTMLDivElement>()
)
<div ref={correctRefs[index]} />
```
해당 방식의 로깅 확인결과 첫 초기 렌더링 시 ref.current가 null인 상태이며,
ref가 연결되기 전 스크롤을 시도하면 실패하는 문제가 있었습니다.
```
[{…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {current: null}
1: {current: null}
2: {current: null}
3: {current: null}
4: {current: null}
5: {current: null}
6: {current: null}
length: 7
```
---
useRef([])와 콜백 ref를 사용하여 ref 배열을 직접 관리하도록 구조를 변경했습니다:
```ts
const correctRefs = useRef<(HTMLDivElement | null)[]>([])
<div
ref={el => {
correctRefs.current[index] = el
}}
/>
```
콜백 ref 방식은 DOM이 mount된 직후에만 ref.current가 할당되므로,
첫 렌더링 시점에도 …
=> [#202] speller-refs-context 초기 렌더링 시 스크롤 동작 안됨 오류 수정 제안

src/entities/speller/index.ts, src/entities/speller/lib/apply-method-color.ts, src/entities/speller/lib/get-method-color.ts, src/entities/speller/model/speller-schema.ts, src/pages/results/ui/bullet-badge.tsx, src/pages/results/ui/custom-text-editor-content.tsx, src/pages/results/ui/spelling-correction-text.tsx
- 오류 구분 색상을 요구 사항에 맞게 변경했습니다.
- 하드코딩으로 적용했던 색상을 `applyMethodColor()` 함수로 적용하도록 변경해 관리 포인트를 줄였습니다.
=> design: 오류 구분 색상 변경 (#190)

src/shared/lib/get-break-point.ts, src/shared/lib/google-ad-sense-production.tsx, src/shared/lib/google-ad-sense.tsx, src/shared/ui/footer-ad-sense.tsx, src/shared/ui/main-ad-sense.tsx
프로덕션과 리모트의 src/shared/lib/google-ad-sense.tsx 파일이 다른 상태로, 자세한 내용은 #208 이슈에 기재하였으며
프로덕션에 적용된 파일은 src/shared/lib/google-ad-sense-production.tsx 로 추가하였습니다. 
이 파일은 이력 관리 및 참고용으로만 사용되며, 광고 관련 기능이 안정화되면 제거할 예정입니다.
현재 PR에 포함된 수정 코드는 @jeongbaebang 님께서 프로덕션에 적용된 내용을 참고해 개선해 주셨습니다.🙂
아래는 정배님께 슬랙으로 공유 받은 변경 사항입니다.
- 반응형 광고 사이즈 문제 해결: 화면 크기 변경 시 광고가 다시 로드되도록 React key를 활용해 리렌더링 처리
- 모바일 광고 미출력 개선: 모바일 너비에서도 광고가 정상 노출되도록 조건 분기 로직 수정
- 광고 스크립트 안정성 확보: adsbygoogle이 준비될 때까지 polling 후 push, 불필요한 로직 제거로 코드 정리
close #208
=> fix: 화면 크기 변경 시 광고가 다시 로드되도록 수정 및 모바일에서 광고 표시 (#208)

src/shared/lib/google-ad-sense.tsx, src/shared/lib/use-ad-retry-key.ts, src/shared/lib/use-break-point.ts, src/shared/ui/footer-ad-sense.tsx, src/shared/ui/main-ad-sense.tsx
- 간헐적으로 data-ad-status="unfilled" 상태에 도달할 경우 광고가 더 이상 로드되지 않는 문제를 해결했습니다.
→ 광고 컴포넌트를 최대 3회까지 자동 재시도하여 새로고침 없이도 광고가 노출될 수 있도록 개선하였습니다.
- 광고가 사용자의 뷰포트에 실제로 진입했을 때만 로드되도록 최적화하여, 초기 로딩 성능 개선 및 UX 향상을 유도했습니다.
- 중복 로직을 useBreakpoint, useAdRetryKey 등의 커스텀 훅으로 분리하여 재사용성과 유지보수성을 높였습니다.
- 모바일 환경에서 광고 게재율 테스트를 위해 최소 높이 및 너비 기준을 임시 조정했습니다.
- 상태가 `filled` 또는 `unfilled`로 확인되면 즉시 처리 후 폴링을 중단하도록 최적화하였습니다.
- 불필요한 반복을 방지하고, 광고 로드 성공 여부를 빠르게 판별할 수 있도록 개선했습니다.
- SPA 전환 환경에서도 광고가 정상적으로 갱신되어 수익 누락 방지하도록 처리하였습니다.
https://github.com/user-attachments/assets/8e769feb-2a80-452a-b5f2-763207078658
⸻
-  IntersectionObserver 기반: 뷰포트 진입 시에만 광고 로딩
- adsbygoogle 스크립트 준비 여부를 polling하여 정확한 push 시점 제어
- 광고 push 후 data-ad-status 값을 통해 실제 광고 로드 성공 여부 판단
- onAdFilled, onAdUnfilled 콜백을 통해 광고 상태 외부에서 핸들링 가능
- key 변경을 통해 컴포넌트 리마운트 …
=> [#217]: 뷰포트 기반 Google AdSense 광고 로딩 및 자동 재시도 로직 구현

app/global-error.tsx
- 전역 에러 발생 시 렌더링되는 UI 컴포넌트의 레이아웃 및 간격을 조정하여, 전체 UI와의 일체감을 개선했습니다.
적용전 
적용후
=> [#218] global-error 컴포넌트 간격 및 스타일 개선

next.config.ts, package-lock.json, package.json, src/app/index.tsx, src/entities/report/ui/report-form-content.tsx, src/entities/report/ui/report-form.tsx, src/entities/speller/index.ts, src/entities/speller/lib/get-corrected-error-type.ts, src/entities/speller/lib/use-strict-check-query.ts, src/entities/speller/ui/speller-setting.tsx, src/pages/results/ui/custom-text-editor-content.tsx, src/pages/results/ui/error-info-section.tsx, src/pages/results/ui/help-section.tsx, src/pages/results/ui/spelling-correction-text.tsx, src/pages/speller/api/spell-check-action.ts, src/pages/speller/ui/speller-control.tsx, src/pages/speller/ui/speller-page.tsx, src/shared/lib/analytics-event-types.ts, src/shared/lib/google-analytics-script.tsx, src/shared/lib/send-ga-event.ts
맞춤법 검사기 서비스에 GA4 기반 주요 사용자 행동 이벤트를 추가하여
초기 사용 흐름 파악, 에러 현황 진단, UI 상호작용률 수집이 가능하도록 구성했습니다.
1. 검사 흐름 전반 측정
- 검사 요청 시점: check_triggered 이벤트 전송
- 검사 완료 시점: check_completed 이벤트 전송
-검사 처리 시간(ms): elapsed_time_ms 파라미터로 측정
2. 에러 발생 시 GA 로깅
- check_result_response_error: 서버 응답 실패 또는 타임아웃 발생 시 로깅
- check_result_response_unknown: 예외 또는 클라이언트 측 처리 실패 시 로깅
- 오류 코드 (error_code), 단계 (error_stage) 등 상세 정보 포함
3. 도움말 클릭률
- ‘자세히 보기’ 클릭 시 error_detail_opened / error_detail_closed 이벤트 전송
4. 대치어 수정 클릭률
- 왼쪽/오른쪽 화면에서의 대치어 수정 클릭시 correction_word_clicked 이벤트 전송
(대치어 리스트 단어 클릭은 1차에서 제외되었습니다.)
5. 오류 제보 버튼 클릭 및 전송률
- 오류 제보 버튼 클릭 시 correction_feedback_opened
- 실제 전송 시 correction_feedback_submitted
→ 오류 유형, 제보 길이, 섹션 정보 포함
6. 대치어 직접 수정률
- 사용자가 대치어를 직접 입력 후 제출한 경우 manual_correction_submitted 이벤트 전송
불필요한 파라미터나 흐름을 일부 …
=> [#213] GA4 1차 이벤트 측정 기능 도입
